---

services:
  minecraft:
    environment:
      CF_MODPACK_ZIP: "/extras/stone-technology-ultimate.zip"
      CF_PAGE_URL: "https://www.curseforge.com/minecraft/modpacks/stone-technology-ultimate"
      CF_FORCE_INCLUDE_MODS: "520110,499826"
      EULA: "TRUE"
      GID: "1000"
      LEVEL_TYPE: "skyblockbuilder:skyblock"
      MEMORY: "6G"
      UID: "1000"
      MODPACK_PLATFORM: "AUTO_CURSEFORGE"
      MOTD: "Stone Technology Ultimate"
      OPS: |
        davidosomething
      TZ: America/New_York
    image: itzg/minecraft-server:java17
    labels:
      glance.category: stu
      glance.description: "Stone Technology Ultimate modpack"
      glance.icon: di:minecraft
      glance.name: STU
    ports:
      - "25566:25565"
    stdin_open: true
    tty: true
    userns_mode: "host"
    volumes:
      - ./data:/data:Z
      - ./extras:/extras:Z
