---

services:
  minecraft:
    environment:
      EULA: "TRUE"
      GID: "1000"
      LEVEL_TYPE: "skyblockbuilder:skyblock"
      MEMORY: "6G"
      MOTD: "Stone Technology Ultimate"
      OPS: |
        davidosomething
      TZ: America/New_York
      TYPE: "FORGE"
      UID: "1000"
      VERSION: "1.18.2"
    image: itzg/minecraft-server:java17
    labels:
      glance.category: stu
      glance.description: "Stone Technology Ultimate modpack"
      glance.icon: di:minecraft
      glance.name: STU
    ports:
      - "25566:25565"
    stdin_open: true
    tty: true
    userns_mode: "host"
    volumes:
      - ./data:/data:Z
